export * as AccountController from './AccountController.js'
export * as StudentController from './StudentController.js'
export * as TeacherController from './TeacherController.js'
export * as GroupController from './GroupController.js'
export * as CourseController from './CourseController.js'
export * as TaskController from './TaskController.js'
export * as StudentAnswerController from './StudentAnswerController.js'